version: '3.4'

services:
  postgres:
    image: postgres:bookworm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenantd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
