table! {
    /// Representation of the `principals` table.
    ///
    /// (Automatically generated by Diesel.)
    principals (id) {
        /// The `id` column of the `principals` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `tenant_id` column of the `principals` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `p_name` column of the `principals` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        p_name -> Varchar,
        /// The `email` column of the `principals` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Nullable<Varchar>,
        /// The `email_confirmed` column of the `principals` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_confirmed -> Nullable<Bool>,
    }
}

table! {
    /// Representation of the `principals_pks` table.
    ///
    /// (Automatically generated by Diesel.)
    principals_pks (p_id, fingerprint) {
        /// The `p_id` column of the `principals_pks` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        p_id -> Uuid,
        /// The `fingerprint` column of the `principals_pks` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        fingerprint -> Varchar,
    }
}

table! {
    /// Representation of the `public_keys` table.
    ///
    /// (Automatically generated by Diesel.)
    public_keys (fingerprint) {
        /// The `fingerprint` column of the `public_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        fingerprint -> Varchar,
        /// The `public_key` column of the `public_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        public_key -> Varchar,
        /// The `public_key_pem` column of the `public_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        public_key_pem -> Varchar,
        /// The `public_key_paserk` column of the `public_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        public_key_paserk -> Varchar,
    }
}

table! {
    /// Representation of the `tenants` table.
    ///
    /// (Automatically generated by Diesel.)
    tenants (id) {
        /// The `id` column of the `tenants` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `tenants` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
    }
}

table! {
    /// Representation of the `user_confirmations` table.
    ///
    /// (Automatically generated by Diesel.)
    user_confirmations (p_id) {
        /// The `p_id` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        p_id -> Uuid,
        /// The `tenant_id` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `token` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Varchar,
        /// The `email` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
    }
}

joinable!(principals -> tenants (tenant_id));
joinable!(principals_pks -> principals (p_id));
joinable!(principals_pks -> public_keys (fingerprint));
joinable!(user_confirmations -> principals (p_id));
joinable!(user_confirmations -> tenants (tenant_id));

allow_tables_to_appear_in_same_query!(
    principals,
    principals_pks,
    public_keys,
    tenants,
    user_confirmations,
);
