table! {
    /// Representation of the `known_permissions` table.
    ///
    /// (Automatically generated by Diesel.)
    known_permissions (tenant_id, permission) {
        /// The `tenant_id` column of the `known_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `permission` column of the `known_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        permission -> Varchar,
    }
}

table! {
    /// Representation of the `policies` table.
    ///
    /// (Automatically generated by Diesel.)
    policies (id) {
        /// The `id` column of the `policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `tenant_id` column of the `policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `name` column of the `policies` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
    }
}

table! {
    /// Representation of the `policy_permissions` table.
    ///
    /// (Automatically generated by Diesel.)
    policy_permissions (policy_id, permission) {
        /// The `policy_id` column of the `policy_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        policy_id -> Uuid,
        /// The `tenant_id` column of the `policy_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `permission` column of the `policy_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        permission -> Varchar,
    }
}

table! {
    /// Representation of the `tenants` table.
    ///
    /// (Automatically generated by Diesel.)
    tenants (id) {
        /// The `id` column of the `tenants` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `tenants` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
    }
}

table! {
    /// Representation of the `user_confirmations` table.
    ///
    /// (Automatically generated by Diesel.)
    user_confirmations (user_id) {
        /// The `user_id` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `tenant_id` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `token` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Varchar,
        /// The `email` column of the `user_confirmations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
    }
}

table! {
    /// Representation of the `user_permissions` table.
    ///
    /// (Automatically generated by Diesel.)
    user_permissions (user_id, tenant_id, permission) {
        /// The `tenant_id` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `user_id` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `permission` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        permission -> Varchar,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `tenant_id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Uuid,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Varchar,
        /// The `pwhash` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        pwhash -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `email_confirmed` column of the `users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        email_confirmed -> Bool,
    }
}

joinable!(policy_permissions -> policies (policy_id));
joinable!(user_confirmations -> tenants (tenant_id));
joinable!(user_confirmations -> users (user_id));
joinable!(user_permissions -> users (user_id));
joinable!(users -> tenants (tenant_id));

allow_tables_to_appear_in_same_query!(
    known_permissions,
    policies,
    policy_permissions,
    tenants,
    user_confirmations,
    user_permissions,
    users,
);
