//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "principal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub email_confirmed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::public_key::Entity> for Entity {
    fn to() -> RelationDef {
        super::principals_public_keys::Relation::PublicKey.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::principals_public_keys::Relation::Principal
                .def()
                .rev(),
        )
    }
}

impl Related<super::tenant::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_confirmations::Relation::Tenant.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_confirmations::Relation::Principal.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
