//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "public_key")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fingerprint: String,
    pub key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::principal::Entity> for Entity {
    fn to() -> RelationDef {
        super::principals_public_keys::Relation::Principal.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::principals_public_keys::Relation::PublicKey
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
